server:
  port: 9001
spring.cloud.stream:
  function.definition: cargoHandlingChannel2
  binders:
    kafka:
      type: kafka
      environment:
         spring:
           cloud:
             stream:
              kafka:
                binder.brokers: localhost:9092
                binder.jaas.loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
                binder.jaas.options.username: admin
                binder.jaas.options.password: admin-secret
    bindings:     
        cargoHandlingChannel2:
          destination: cargoHandlings2
          binder: kafka
          group: cargoHandlingsQueue2
          contentType: 'application/json'
    kafka.binder:
      configuration:
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN   
