server:
  port: 9001
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:     
        cargoHandlingChannel2:
          destination: cargoHandlings2
          group: cargoHandlingsQueue2   
          contentType: 'application/json'